# SPDX-FileCopyrightText: 2024-Present =TypicalCrusader <typicalcrusader@noreply.codeberg.org>
#
# SPDX-License-Identifier: GPL-2.0-only

BCH-init:
	echo "[PY]	BUILDING INITIAL BCH"
	python "BCH-init.py"