# SPDX-FileCopyrightText: 2024-Present =TypicalCrusader <typicalcrusader@noreply.codeberg.org>
#
# SPDX-License-Identifier: GPL-2.0-only

BINion-Maker:
	echo "[PY]	PARSING BINIONS"
#python "./BINion-Parser/BINion-Parser.py"